// ---------------------------------------------------------------------------------------
// This File (Func_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "Types\Typeclass\Functor.h"
#include "Types\Typeclass\Applicative.h"
#include "Types\Typeclass\Monad.h"
#include "Types\Typeclass\Semigroup.h"
#include "Types\Typeclass\Monoid.h"

 /*Added Typeclass Functor Instance Func*/ 
 ;

 /*Added Typeclass Applicative Instance Func*/ 
 ;

 /*Added Typeclass Monad Instance Func*/ 
 ;

 /*Added Typeclass Semigroup Instance Func*/ 
 ;

 /*Added Typeclass Monoid Instance Func*/ 
 ;
