// ---------------------------------------------------------------------------------------
// This File (Enum_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "MacroUtils.h"
#include "Functional\Prelude.h"
#include "Functional\Typeclass.h"
#include "Types\Unpack.h"
class IEnum {
	public: const Arr<const VStar&, VStar > toEnum() const; private: virtual VStar _toEnum ( const VStar& integer ) const = 0;
	public: const Arr<const VStar&, Int > fromEnum() const; private: virtual Int _fromEnum ( const VStar& value ) const = 0;
	public: const Arr<const VStar&, VStar > succ() const; private: virtual VStar _succ ( const VStar& value ) const ;
	public: const Arr<const VStar&, VStar > pred() const; private: virtual VStar _pred ( const VStar& value ) const ;
};
