// ---------------------------------------------------------------------------------------
// This File (Eq_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "MacroUtils.h"
#include "Functional\Prelude.h"
#include "Functional\Typeclass.h"
#include "Types\Unpack.h"
;
class IEq {
	public: const Arr<const VStar&, Arr<const VStar&, Bool > > eq() const; private: virtual Bool _eq ( const VStar& a , const VStar& b ) const = 0;
	public: const Arr<const VStar&, Arr<const VStar&, Bool > > neq() const; private: virtual Bool _neq ( const VStar& a , const VStar& b ) const ;
};
