// ---------------------------------------------------------------------------------------
// This File (Monoid_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "MacroUtils.h"
#include "Functional\Prelude.h"
#include "Functional\Typeclass.h"
#include "Types\Unpack.h"
#include "Types/Typeclass/Semigroup_gen.h"
;
class IMonoid : public virtual ISemigroup {
	public: const Arr<void, VStar > mempty() const { return curry([this]( ) -> VStar { return this->_mempty ( ); }); }; private: virtual VStar _mempty ( ) const = 0;
	public: const Arr<const VStar&, VStar > memptyV() const { return curry([this]( const VStar& monoid ) -> VStar { return this->_memptyV ( monoid ); }); }; private: virtual VStar _memptyV ( const VStar& monoid ) const { return monoid.getTypeclass()->Monoid->mempty(); }
};
