// ---------------------------------------------------------------------------------------
// This File (Show_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "MacroUtils.h"
#include "Functional\Prelude.h"
#include "Functional\Typeclass.h"
#include "Types\Unpack.h"
class IShow {
	public: const Arr<const VStar&, FString > show() const { return curry([this]( const VStar& a ) -> FString { return this->_show ( a ); }); }; private: virtual FString _show ( const VStar& a ) const = 0;
};
