#pragma once

#include "Preprocess/Include.h"


// Templating
#define _TEMPLATE_LOOP(A) , class A
#define OPT_TEMPLATE(...) NULLARY( (template <MAP_LIST(_TEMPLATE_LOOP, __VA_ARGS__)>), (), __VA_ARGS__)
#define TEMPLATE(...) NULLARY( (template <MAP_LIST(_TEMPLATE_LOOP, __VA_ARGS__)>), (template <>), __VA_ARGS__)
#define STRICT_TEMPLATE(...) template <NULLARY((MAP_LIST(_TEMPLATE_LOOP, __VA_ARGS__)), (class = auto), __VA_ARGS__)> 

#define _LIST_LOOP(A) , A
#define TEMPLATE_INST(...) NULLARY( (<MAP_LIST(_LIST_LOOP, __VA_ARGS__)>), (), __VA_ARGS__)

// Defining Function Implementation and their Curried Versions
#define FUNC_DEFN(TEMPLATES, FUNCNAME, DEFN) \
STRICT_TEMPLATE(UNBRACKET TEMPLATES)			PP__NEWLINE \
inline static auto FUNCNAME = UNBRACKET DEFN;	PP__NEWLINE 

#define CURRY_DEFN(TEMPLATES, FUNCNAME) FUNC_DEFN(TEMPLATES, FUNCNAME, (curry(_##FUNCNAME<MAP_LIST(_LIST_LOOP, UNBRACKET TEMPLATES)>)))

// Defining both a Function Implementation and Definition
#define TYPECLASS_FUNC(TEMPLATES, FUNCNAME, DEFN)	PP__NEWLINE \
private:											PP__NEWLINE \
	FUNC_DEFN(TEMPLATES, _## FUNCNAME, DEFN)		PP__NEWLINE \
public:												PP__NEWLINE \
	CURRY_DEFN(TEMPLATES, FUNCNAME)

// Defining an Optional Typeclass Function
#define TYPECLASS_OPT_FUNC(TEMPLATES, FUNCNAME, DEFN) NULLARY((TYPECLASS_FUNC(TEMPLATES, FUNCNAME, DEFN)), (), UNBRACKET DEFN)

// Defining a Typeclass Template
#define TYPECLASS_WRAP_DEFN(CLS, TEMPLATES, INSTANCE) class CLS<INSTANCE TEMPLATE_INST(UNBRACKET TEMPLATES)> : public Base##CLS<INSTANCE,UNBRACKET TEMPLATES>

#define TYPECLASS_STATIC_DEFN(CLS, TEMPLATES, INSTANCE) class CLS<INSTANCE> : public Base##CLS<INSTANCE>

#define TYPECLASS_DEFN(CLS, TEMPLATES, INSTANCE) NULLARY((TYPECLASS_WRAP_DEFN),(TYPECLASS_STATIC_DEFN), UNBRACKET TEMPLATES)(CLS, TEMPLATES, INSTANCE)

// Defining a Typeclass Template Signature
//#define TYPECLASS_DEFN_FUNC(TEMPLATES, SIGNATURE, NAME)