// ---------------------------------------------------------------------------------------
// This File (Int_gen.h) is automatically generated by Preprocess.tt using T4 Text Transformer
// ANY changes made to this file directly are liable to be overwritten on compile
// If this file needs to be edited, Types.tt will need to be extended in its functionality
// ---------------------------- Start AutoGenerated File ---------------------------------
#pragma once
#include "C:\\Users\\v2tac\\Desktop\\UNI\\Semester 8\\FIT444X - Honours Thesis\\Unreal\\HonoursProj/Source/HonoursProj\\Types/Ord.h"
template <typename A>
class Number {
private:
	A _value;
	friend class Ordinal<Number<A>>;
public:
	Number(A value) { _value = value; }
	A get() { return _value; }
};

 /*Added Typeclass Ordinal Instance Number*/ 
 template <class A> 
 class Ordinal<Number <A> > : public BaseOrdinal<Number <A> > { 
 private: 
 template <class = auto> 
 inline static auto _ord = [](Number<A> a, Number<A> b) -> ORD { 
 return a._value == b._value ? ORD::EQ : a._value < b._value ? ORD::LT : ORD::GT; 
 }; 
 public: 
 template <class = auto> 
 inline static auto ord = curry(_ord<>); 
 };
;
